Adding mandatory yaml files
philips-forks/oauth2-proxy pull request #35
Opened 2023-06-28 15:32 UTC by lucasrf

## Description

Adding mandatory yaml files:
- readme
- codeowners
- philips-repo.yaml
- catalog-info.yaml
- mkdocs.yml

## Motivation and Context

[Add mandatory yaml files to repo story](https://tfsemea1.ta.philips.com/tfs/TPC_Region11/Healthcare%20IT/_boards/board/t/CVI%20Reporting%20Spartans/Stories/?workitem=1507539)

2023-06-29 09:51 UTC, FerdySchepers requested changes

2023-06-29 09:51 UTC, FerdySchepers commented on catalog-info.yaml
> +  component: Reporting
component reporting changed into system please change to:
system: Reporting

2023-06-29 09:51 UTC, FerdySchepers commented on catalog-info.yaml
> +  annotations:
add:
title: Oauth2-Proxy

2023-06-29 09:51 UTC, FerdySchepers commented on catalog-info.yaml
> +  description: TBD
Maybe add some info from the readme file:
A reverse proxy and static file server that provides authentication using Providers (Google, GitHub, and others) to validate accounts by email, domain or group.

Note: This repository was forked from [bitly/OAuth2_Proxy](https://github.com/bitly/oauth2_proxy) on 27/11/2018. Versions v3.0.0 and up are from this fork and will have diverged from any changes in the original fork. A list of changes can be seen in the [CHANGELOG](https://github.com/philips-forks/oauth2-proxy/blob/master/CHANGELOG.md).

2023-06-29 09:51 UTC, FerdySchepers commented on catalog-info.yaml
> +    github.com/project-slug: philips-forks/oauth2-proxy
add:  backstage.io/techdocs-ref: dir:.

2023-06-30 14:18 UTC, FerdySchepers approved these changes

2023-06-30 14:18 UTC, merged

2023-06-30 14:24 UTC, FerdySchepers commented on mkdocs.yml
> +
nav:
  - ...
plugins:
  - techdocs-core
  - awesome-pages
  
Should be added if we automatically wnt to generate the doc files

2023-06-30 16:35 UTC, l-lafin commented
@lucasrf @FerdySchepers @sailinder, this repository belongs to the `philips-forks` and not `philips-internal`, and as a consequence it is not connected to the dev-portal. The files added here must be removed.